include:
  - template: Code-Quality.gitlab-ci.yml

image: gradle:8.6-jdk17

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"

stages:
  - build
  - test
  - report
  - deploy

before_script:
  - chmod +x gradlew



build:
  stage: build
  script:
    - ./gradlew assemble
  cache:
    key: "${CI_COMMIT_REF_SLUG}"
    policy: push
    paths:
      - .gradle/
      - build/



test:
  stage: test
  script:
    - ./gradlew test jacocoTestReport
  artifacts:
    when: always
    expose_as: "Jacoco Test Report"
    paths:
      - build/jacoco/jacoco.xml
    reports:
      junit: build/test-results/test/**/TEST-*.xml



code_quality:
  stage: test
  allow_failure: false
  variables:
    CODE_QUALITY_IMAGE: "registry.gitlab.com/gitlab-org/ci-cd/codequality:latest"
  artifacts:
    expose_as: "Code Quality Report"
    paths:
      - gl-code-quality-report.json



code_quality_html:
  extends: code_quality
  variables:
    REPORT_FORMAT: "html"
  artifacts:
    expose_as: "Code Quality Report HTML"
    paths:
      - gl-code-quality-report.html



mutation-coverage:
  stage: test
  needs: ["test"]
  script:
    - ./gradlew pitest
    - tar -czvf build/reports/pitest.tar.gz build/reports/pitest/
  artifacts:
    when: always
    expose_as: "Pitest Mutation Report"
    paths:
      - build/reports/pitest.tar.gz



coverage-jdk17:
  stage: deploy
  image: haynes/jacoco2cobertura:1.0.3
  needs: ["test"]
  script:
    - python /opt/cover2cover.py build/jacoco/jacoco.xml src/main/java > build/cobertura.xml
    - python /opt/source2filename.py build/cobertura.xml
  artifacts:
    expose_as: "Coverage Report"
    paths:
      - build/cobertura.xml
    reports:
      coverage_report:
        coverage_format: cobertura
        path: build/cobertura.xml
